# ==============================================================================
# GoReleaser Configuration
# ==============================================================================
# Handles building, packaging, and releasing the CLI application
# Documentation: https://goreleaser.com/

version: 2

# Project metadata
project_name: lctyper

# Build configuration
builds:
  - id: cli
    main: ./cmd/app
    binary: lctyper
    dir: apps/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}
      - -X main.buildBy=goreleaser

# Archive configuration
archives:
  - id: cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

# Checksum file generation
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Snapshot builds (for non-tagged commits)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog generation
changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"

# GitLab Release configuration
gitlab_urls:
  # Uses GitLab CI/CD built-in variables
  api: https://gitlab.com/api/v4/
  download: https://gitlab.com
  # skip_tls_verify: false

release:
  gitlab:
    owner: "{{ .Env.CI_PROJECT_NAMESPACE }}"
    name: "{{ .Env.CI_PROJECT_NAME }}"
  # Release name template
  name_template: "{{.ProjectName}} {{.Version}}"
  # Prerelease configuration
  prerelease: auto
  # Release mode
  mode: replace
  # Draft release
  draft: false
  # Discussion category
  # discussion_category_name: Releases
# Announce release (optional - can be configured later)
# announce:
#   skip: '{{gt .Patch 0}}'  # Skip patch releases
