build:cli:
  stage: build
  image: golang:1.25
  script:
    - cd apps/cli
    - go mod tidy
    - go build -v -o cdns cmd/app/main.go
  artifacts:
    paths:
      - apps/cli/cdns
    expire_in: 1 week

build:docs:
  stage: build
  image: node:20-alpine
  script:
    - cd apps/documentation
    - npm install -g pnpm
    - pnpm install --frozen-lockfile
    - pnpm build
  artifacts:
    paths:
      - apps/documentation/build
    expire_in: 1 week
